#!/bin/bash
#SBATCH -J jacobi-omp           # job name
#SBATCH -o jacobi-omp%j       # output and error file name (%j expands to jobID)
#SBATCH -n 16              # total number of mpi tasks requested
#SBATCH -p development     # queue (partition) -- normal, development, etc.
#SBATCH -t 01:30:00        # run time (hh:mm:ss) - 1.5 hours
#SBATCH --mail-user=dh1806@nyu.edu
#SBATCH --mail-type=end    # email me when the job finishes
#SBATCH -A TG-ASC150003    # account number

export OMP_NUM_THREADS=4
./jacobi-omp 5000 100
