#!/bin/bash
#SBATCH -J gsOMP           # job name
#SBATCH -o gsOMP%j       # output and error file name (%j expands to jobID)
#SBATCH -n 16              # total number of mpi tasks requested
#SBATCH -p development     # queue (partition) -- normal, development, etc.
#SBATCH -t 01:30:00        # run time (hh:mm:ss) - 1.5 hours
#SBATCH --mail-user=darshan.hegde@cims.nyu.edu
#SBATCH --mail-type=begin  # email me when the job starts
#SBATCH --mail-type=end    # email me when the job finishes
#SBATCH -A TG-ASC150003    # account number
#OMP_NUM_THREADS=2
ibrun ./gs-omp.o 1000 500000              # run the MPI executable
